# Generated by Django 3.1.1 on 2020-09-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
