# Generated by Django 3.1.1 on 2020-09-18 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 21, 3, 47, 848436)),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 18, 21, 3, 47, 790601)),
        ),
    ]
