# Generated by Django 3.1.1 on 2020-09-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20200918_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
