# Generated by Django 3.1.1 on 2020-09-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0009_auto_20200919_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
