# Generated by Django 3.1.1 on 2020-09-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisplayViewModel',
            new_name='AjaxModel',
        ),
    ]
