# Generated by Django 3.1.1 on 2020-09-27 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField()),
                ('language', models.CharField(max_length=50, null=True, verbose_name='Favorite Programming language')),
                ('programmer', models.BooleanField(default=False, verbose_name='Likes Programming or not?')),
            ],
        ),
    ]
