# Generated by Django 3.1.1 on 2020-09-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_forms', '0002_auto_20200911_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawform',
            name='age',
            field=models.IntegerField(help_text='Enter your age', verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='rawform',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='rawform',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter your email', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='rawform',
            name='language',
            field=models.CharField(blank=True, help_text='Enter your favorite programming language', max_length=50, null=True, verbose_name='Favorite Programming language'),
        ),
        migrations.AlterField(
            model_name='rawform',
            name='name',
            field=models.CharField(help_text='Enter your name', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rawform',
            name='programmer',
            field=models.BooleanField(default=False, verbose_name='Likes Programming or not?'),
        ),
    ]
