# Generated by Django 3.1.1 on 2020-09-16 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_forms', '0004_auto_20200916_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawform',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Age'),
        ),
    ]
